version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./mysql/transaction.ddl:/var/ddl/transaction.ddl
      - ./mysql/master.ddl:/var/ddl/master.ddl
      - ./mysql/master.dml:/var/dml/master.dml
      - ./script:/var/script
    ports:
      - 3306:3306
